### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by bananakid** [0xC0000054/pdn-jpegxl#4]
While [pdn-jpegxl](https://github.com/0xC0000054/pdn-jpegxl) 1.0.5 release claims to be compatible with paint.net 5.0, it appears that it actually requires paint.net 5.0.11+ (as it refuses to work in 5.0.10). I hope this can be addressed as some other plugins that aren't actively maintained require 5.0.10 at most. I will have to use [pdn-jpegxl](https://github.com/0xC0000054/pdn-jpegxl) 1.0.4 release for the time being.

**Comment by 0xC0000054** [comment]
5.0.11 was the latest version of Paint.NET at the time that version 1.0.5 of the plugin was released. I don't update the minimum requirements for every release of Paint.NET because I assume that people will be using the latest version.

Broken plugins should be reported on the Paint.NET forum, and there may also be updated versions or an alternative that works in the newer version of Paint.NET.

**Comment by 0xC0000054** [comment]
I removed the version reference from README.md, as it only applied to the source code. I also updated the Release descriptions with the Paint.NET 5.0 versions.
